spring:
  application:
    name: registry-server
  cloud:
    config:
      fail-fast: true
      password: password
      username: user
  config:
    import: optional:configserver:http://localhost:9099
