# Data Source setting
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mister_keeper_book
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        ddl-auto: update
    show-sql: true


security:
  oauth2:
    client:
      clientId: book-service
      clientSecret: ${ACCOUNT_SERVICE_SECRET}
      accessTokenUri: http://auth-service:6000/uaa/oauth/token
      grant-type: password
      scope: server

server:
  servlet:
    context-path: /books
  port: 6005

feign:
  hystrix:
    enabled: true
