server:
  port: 9099

spring:
  application:
    name: config-server
  security:
    user:
      name: user
      password: password
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/services
  profiles:
    active: native
